# Site wide configuration
title: Open311
description:
url: 
production_url: //wiki.open311.org

#Github Repo
repo_name: open311.github.io
branch: master
org_name: open311

# Jekyll configuration
permalink: pretty
markdown: kramdown
highlighter: pygments

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"